coverage:
  status:
    project:
      python:
        target: 95%
        flags: python
      C:
        target: 80%
        flags: C

    patch:
      python:
        target: 90%
        flags: python
      C:
        target: 85%
        flags: C
parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: yes
      method: no
      macro: no
